  services:
    app:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      container_name: sms_app
      restart: unless-stopped
      working_dir: /var/www
      volumes:
        - ./:/var/www
        - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
        - sms_network

    webserver:
      image: nginx:alpine
      container_name: sms_webserver
      restart: unless-stopped
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
      networks:
        - sms_network

    db:
      image: mysql:8.0
      container_name: sms_db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: sms_notification
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_PASSWORD: secret
        MYSQL_USER: sms_user
      ports:
        - "3306:3306"
      volumes:
        - sms_db_data:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      networks:
        - sms_network

    redis:
      image: redis:alpine
      container_name: sms_redis
      restart: unless-stopped
      ports:
        - "6379:6379"
      networks:
        - sms_network

    queue:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      container_name: sms_queue
      restart: unless-stopped
      working_dir: /var/www
      command: php artisan queue:work --sleep=3 --tries=3
      volumes:
        - ./:/var/www
      depends_on:
        - app
        - db
        - redis
      networks:
        - sms_network

  networks:
    sms_network:
      driver: bridge

  volumes:
    sms_db_data:
      driver: local
